language: perl
perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"

before_install:
# install tiff
  - sudo apt-get -y purge ruby '^libtiff.*' zlib1g-dev
  - sudo apt-get autoremove
  - sudo apt-get install automake

# install deps
#  - cat ./cpan-deps | cpanm --sudo --notest -v
  - cat ./cpan-deps | cpanm --sudo --notest
  - cat ./cpan-deps
  - dpkg -l

install:
  - perl ./Build.PL --travis 1
#  - sudo ./Build clean
  - cat ./_build/notes
  - sudo ./Build install

script:
  - prove

notifications:
  irc: "irc.perl.org#sdl-xxx"
